spring:
  profiles.active: shota
---
spring:
  profiles: zolota
man:
  name: halya
  surname: yakymchuk
  year: 31
server:
  port: 8888
---
spring:
  profiles: shota
man:
  name: yuriy
  surname: yakymchuk
  year: 28